
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Sedat
 */
public class CalisanEkrani extends javax.swing.JDialog {

    DefaultTableModel model;
    CalisanIslemleri islemler = new CalisanIslemleri();

    /**
     * Creates new form CalisanEkrani
     */
    public CalisanEkrani(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        model = (DefaultTableModel) calisanlar_tablosu.getModel();
        calisanGoruntule();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        calisanlar_tablosu = new javax.swing.JTable();
        mesaj_yazisi = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ad_alani = new javax.swing.JTextField();
        soyad_alani = new javax.swing.JTextField();
        departman_alani = new javax.swing.JTextField();
        maas_alani = new javax.swing.JTextField();
        btnCalisanEkle = new javax.swing.JButton();
        btnGuncelle = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSil = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnKutuTemizle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Çalışanlar Kayıt Uygulaması");
        setMaximumSize(new java.awt.Dimension(1000, 500));
        setMinimumSize(new java.awt.Dimension(1000, 500));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1000, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 500));

        calisanlar_tablosu.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        calisanlar_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Adı", "Soyadı", "Departman", "Maaş"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        calisanlar_tablosu.setGridColor(new java.awt.Color(255, 204, 255));
        calisanlar_tablosu.setName(""); // NOI18N
        calisanlar_tablosu.setRowHeight(22);
        calisanlar_tablosu.setRowMargin(2);
        calisanlar_tablosu.setSelectionBackground(new java.awt.Color(102, 0, 102));
        calisanlar_tablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calisanlar_tablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(calisanlar_tablosu);
        if (calisanlar_tablosu.getColumnModel().getColumnCount() > 0) {
            calisanlar_tablosu.getColumnModel().getColumn(0).setResizable(false);
            calisanlar_tablosu.getColumnModel().getColumn(1).setResizable(false);
            calisanlar_tablosu.getColumnModel().getColumn(2).setResizable(false);
            calisanlar_tablosu.getColumnModel().getColumn(3).setResizable(false);
            calisanlar_tablosu.getColumnModel().getColumn(4).setResizable(false);
        }

        mesaj_yazisi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mesaj_yazisi.setForeground(new java.awt.Color(0, 0, 102));

        jLabel3.setFont(new java.awt.Font("Calibri Light", 0, 15)); // NOI18N
        jLabel3.setText("Departman :");

        jLabel4.setFont(new java.awt.Font("Calibri Light", 0, 15)); // NOI18N
        jLabel4.setText("Maaş :");

        ad_alani.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        soyad_alani.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        departman_alani.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        maas_alani.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        btnCalisanEkle.setFont(new java.awt.Font("Calibri Light", 1, 13)); // NOI18N
        btnCalisanEkle.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sedat\\Desktop\\add.png")); // NOI18N
        btnCalisanEkle.setText("  Yeni Çalışan Ekle");
        btnCalisanEkle.setBorder(null);
        btnCalisanEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalisanEkleActionPerformed(evt);
            }
        });

        btnGuncelle.setFont(new java.awt.Font("Calibri Light", 1, 13)); // NOI18N
        btnGuncelle.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sedat\\Desktop\\update.png")); // NOI18N
        btnGuncelle.setText("  Çalışan Güncelle");
        btnGuncelle.setBorder(null);
        btnGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuncelleActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri Light", 0, 15)); // NOI18N
        jLabel1.setText("Ad :");

        btnSil.setFont(new java.awt.Font("Calibri Light", 1, 13)); // NOI18N
        btnSil.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sedat\\Desktop\\delete.png")); // NOI18N
        btnSil.setText("  Çalışan Sil");
        btnSil.setBorder(null);
        btnSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSilActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri Light", 0, 15)); // NOI18N
        jLabel2.setText("Soyad :");

        btnKutuTemizle.setForeground(new java.awt.Color(102, 0, 51));
        btnKutuTemizle.setText("Kutucukları Temizle");
        btnKutuTemizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKutuTemizleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(departman_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maas_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(soyad_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ad_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mesaj_yazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCalisanEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSil, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 25, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnKutuTemizle, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnKutuTemizle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ad_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(soyad_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(departman_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(maas_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mesaj_yazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSil, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalisanEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnCalisanEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalisanEkleActionPerformed
        mesaj_yazisi.setText("");

        String ad = ad_alani.getText();
        String soyad = soyad_alani.getText();
        String departman = departman_alani.getText();
        String maas = maas_alani.getText();

        if (!(ad.trim().equals("") || soyad.trim().equals("") || departman.trim().equals("") || maas.trim().equals(""))) {

            islemler.calisanEkle(ad, soyad, departman, maas);
            calisanGoruntule();
            mesaj_yazisi.setText("Yeni çalışan başarıyla eklendi.");
        } else {
            JOptionPane.showMessageDialog(this, "Yukarıda ki alanlardan herhangi birisi boş! \n"
                    + "Lütfen gerekli yerleri doldurun.", "Çalışan Ekleme - Uyarı ", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnCalisanEkleActionPerformed

    private void calisanlar_tablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calisanlar_tablosuMouseClicked
        int selectedRow = calisanlar_tablosu.getSelectedRow();

        ad_alani.setText(model.getValueAt(selectedRow, 1).toString());
        soyad_alani.setText(model.getValueAt(selectedRow, 2).toString());
        departman_alani.setText(model.getValueAt(selectedRow, 3).toString());
        maas_alani.setText(model.getValueAt(selectedRow, 4).toString());


    }//GEN-LAST:event_calisanlar_tablosuMouseClicked

    private void btnGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuncelleActionPerformed

        String ad = ad_alani.getText();
        String soyad = soyad_alani.getText();
        String departman = departman_alani.getText();
        String maas = maas_alani.getText();

        int selectedRow = calisanlar_tablosu.getSelectedRow();
        if (selectedRow == -1) {
            if (model.getRowCount() == 0) {
                mesaj_yazisi.setText("Çalışanlar tablosu şuan boş.");
            } else {
                mesaj_yazisi.setText("Lütfen güncellenecek bir çalışan seçin.");
            }
        } else {

            int id = (int) model.getValueAt(selectedRow, 0);

            islemler.calisanGuncelle(id, ad, soyad, departman, maas);
            calisanGoruntule();
            mesaj_yazisi.setText("Çalışan başarıyla güncellendi.");

        }

    }//GEN-LAST:event_btnGuncelleActionPerformed

    private void btnSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSilActionPerformed

        mesaj_yazisi.setText("");

        int selectedRow = calisanlar_tablosu.getSelectedRow();

        if (selectedRow == -1) {
            if (model.getRowCount() == 0) {
                mesaj_yazisi.setText("Çalışan tablosu şu anda boş...");
            } else {
                mesaj_yazisi.setText("Lütfen silinecek bir çalışan seçiniz.");

            }
        } else {
            int id = (int) model.getValueAt(selectedRow, 0);
            int secim = JOptionPane.showConfirmDialog(this, "Silmek istiyor musunuz", "Çalışan Sil", JOptionPane.YES_NO_CANCEL_OPTION);
            if (secim == JOptionPane.YES_OPTION) {
                islemler.calisanSil(id);
                JOptionPane.showMessageDialog(this, calisanlar_tablosu.getValueAt(selectedRow, 1) + " " + calisanlar_tablosu.getValueAt(selectedRow, 2) + " silindi.");
                mesaj_yazisi.setText("" + calisanlar_tablosu.getValueAt(selectedRow, 1) + " " + calisanlar_tablosu.getValueAt(selectedRow, 2) + " çalışanlar listesinden başarıyla silindi.");
                calisanGoruntule();

            } else if (secim == JOptionPane.NO_OPTION) {
                mesaj_yazisi.setText("Çalışan silinmedi...");
            } else {
                mesaj_yazisi.setText("Silmekten vazgeçildi.");
            }

        }

    }//GEN-LAST:event_btnSilActionPerformed

    private void btnKutuTemizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKutuTemizleActionPerformed
        mesaj_yazisi.setText("");
        ad_alani.setText("");
        soyad_alani.setText("");
        departman_alani.setText("");
        maas_alani.setText("");
    }//GEN-LAST:event_btnKutuTemizleActionPerformed

    /**
     * @param args the command line arguments
     */
    public void calisanGoruntule() {
        ad_alani.setText("");
        soyad_alani.setText("");
        departman_alani.setText("");
        maas_alani.setText("");

        model.setRowCount(0);
        ArrayList<Calisan> calisanlar = new ArrayList<Calisan>();

        calisanlar = islemler.calisanlariGetir();

        if (calisanlar != null) {

            for (Calisan calisan : calisanlar) {
                Object[] eklenecek = {
                    calisan.getId(), calisan.getAd(), calisan.getSoyad(),
                    calisan.getDepartman(), calisan.getMaas()};

                model.addRow(eklenecek);
            }
        }

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalisanEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalisanEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalisanEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalisanEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CalisanEkrani dialog = new CalisanEkrani(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad_alani;
    private javax.swing.JButton btnCalisanEkle;
    private javax.swing.JButton btnGuncelle;
    private javax.swing.JButton btnKutuTemizle;
    private javax.swing.JButton btnSil;
    private javax.swing.JTable calisanlar_tablosu;
    private javax.swing.JTextField departman_alani;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField maas_alani;
    private javax.swing.JLabel mesaj_yazisi;
    private javax.swing.JTextField soyad_alani;
    // End of variables declaration//GEN-END:variables
}
