
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Sedat
 */
public class LoginEkrani extends javax.swing.JFrame {

    CalisanIslemleri islemler = new CalisanIslemleri();

    /**
     * Creates new form LoginEkrani
     */
    public LoginEkrani() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kullaniciAdi_txt = new javax.swing.JTextField();
        parola_txt = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        btnGiris = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        mesaj_alani = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_UygulamaHakkinda = new javax.swing.JMenu();
        menuCikisYap = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Giriş Yap - Çalışanlar Kayıt Uygulaması");
        setBounds(new java.awt.Rectangle(400, 200, 0, 0));
        setMaximumSize(new java.awt.Dimension(734, 402));
        setMinimumSize(new java.awt.Dimension(734, 402));
        setSize(new java.awt.Dimension(734, 402));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setMaximumSize(new java.awt.Dimension(734, 402));
        jPanel1.setMinimumSize(new java.awt.Dimension(734, 402));

        kullaniciAdi_txt.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        parola_txt.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 51));
        jLabel1.setText("Kullanıcı adı :");

        btnGiris.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnGiris.setForeground(new java.awt.Color(153, 0, 102));
        btnGiris.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sedat\\Desktop\\loginBtn.png")); // NOI18N
        btnGiris.setText("Giriş Yap");
        btnGiris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGirisActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 51));
        jLabel2.setText("Şifre :");

        mesaj_alani.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        mesaj_alani.setForeground(new java.awt.Color(102, 0, 51));

        jSeparator1.setBackground(new java.awt.Color(102, 0, 51));
        jSeparator1.setForeground(new java.awt.Color(102, 0, 102));

        jPanel2.setBackground(new java.awt.Color(51, 0, 51));

        jLabel3.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Çalışanlar Kayıt Uygulaması");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mesaj_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kullaniciAdi_txt)
                    .addComponent(parola_txt)
                    .addComponent(btnGiris, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(kullaniciAdi_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addComponent(mesaj_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(parola_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(36, 36, 36)
                .addComponent(btnGiris)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menu_UygulamaHakkinda.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sedat\\Desktop\\about.png")); // NOI18N
        menu_UygulamaHakkinda.setText("Uygulama hakkında");
        menu_UygulamaHakkinda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_UygulamaHakkindaMouseClicked(evt);
            }
        });
        jMenuBar1.add(menu_UygulamaHakkinda);

        menuCikisYap.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sedat\\Desktop\\q.png")); // NOI18N
        menuCikisYap.setText("Çıkış Yap");
        menuCikisYap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCikisYapMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuCikisYap);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGirisActionPerformed
        mesaj_alani.setText("");
        String kullanici_adi = kullaniciAdi_txt.getText();
        String parola = new String(parola_txt.getPassword());

        boolean girisbasarili = islemler.girisYap(kullanici_adi, parola);

        if (girisbasarili) {
            CalisanEkrani calisanekrani = new CalisanEkrani(this, true);

            setVisible(false);
            calisanekrani.setVisible(true);
            System.exit(0);

        } else {
            mesaj_alani.setText("Giriş başarısız!\n"
                    + " Lütfen tekrar deneyin.");
            JOptionPane.showMessageDialog(this, " (1)* Kullanıcı adı veya Şifreniz hatalı. \n",
                     "Giriş Başarısız", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnGirisActionPerformed

    private void menuCikisYapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCikisYapMouseClicked
        System.exit(0);
    }//GEN-LAST:event_menuCikisYapMouseClicked

    private void menu_UygulamaHakkindaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_UygulamaHakkindaMouseClicked
        JOptionPane.showMessageDialog(this, "Çalışanlar Kayıt Uygulaması , Java OOP çalışmam sonucunda \n MySQL & Swing kullanılarak basit olmak amacıyla geliştirilmiştir. / Sedat Başpınar", "Uygulama hakkında", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_menu_UygulamaHakkindaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGiris;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField kullaniciAdi_txt;
    private javax.swing.JMenu menuCikisYap;
    private javax.swing.JMenu menu_UygulamaHakkinda;
    private javax.swing.JLabel mesaj_alani;
    private javax.swing.JPasswordField parola_txt;
    // End of variables declaration//GEN-END:variables
}
